# Generated by Django 4.1.6 on 2023-02-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_profile_profileimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profileimg",
            field=models.ImageField(default="blank.png", upload_to="profile_images"),
        ),
    ]
